language: c # NOTE: this will set CC=gcc which might cause trouble
before_script:
  ## Install toolchain for mc1233x in care-free way
  - "[ $BUILD_TYPE = multi ] && curl -s \
       https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2008q3-66-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 \
         | tar xjf - -C /tmp/ && sudo cp -f -r /tmp/arm-2008q3/* /usr/ && rm -rf /tmp/arm-2008q3 && arm-none-eabi-gcc --version || true"
  ## Compile cooja.jar when we need it. This needs to exit with 0, otherwise Travis will complain that it failed.
  - "[ $BUILD_TYPE = cooja ] && ant -q -f tools/cooja/build.xml jar || true"
  ## Both build types require msp430 toolchain
  - "sudo apt-get update && sudo apt-get install gcc-msp430 || true"

script:
  - "make -f .travis.mk $MAKE_TARGETS; echo 'Summary:'; cat results | sort | uniq -c; grep -v -q 'fail' results"

env:
  - BUILD_TYPE='cooja' MAKE_TARGETS='cooja' TAIL=cat
  - BUILD_TYPE='multi' MAKE_TARGETS='native minimal-net redbee-econotag'
