language: c # NOTE: this will set CC=gcc which might cause trouble
branches:
  only:
    - travis
    - travis_testme
before_script:
  ## Install toolchain for mc1233x in care-free way
  - "curl -s \
       https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2008q3-66-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 \
         | tar xjf - -C /tmp/ && sudo cp -f -r /tmp/arm-2008q3/* /usr/ && rm -rf /tmp/arm-2008q3 && arm-none-eabi-gcc --version"
script:
  - "make -f Makefile.CI native minimal-net redbee-econotag"
